" DO NOT EDIT THIS FILE
" Add your own customizations in /opt/vim_runtime/my_configs.vim

set runtimepath+=/opt/vim_runtime

source /opt/vim_runtime/vimrcs/basic.vim
source /opt/vim_runtime/vimrcs/filetypes.vim
source /opt/vim_runtime/vimrcs/plugins_config.vim
source /opt/vim_runtime/vimrcs/extended.vim
try
  source /opt/vim_runtime/my_configs.vim
catch
endtry

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

set number
colorscheme dracula
set shell=/bin/zsh

